version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Listing contents..."
      - Get-ChildItem -Recurse
      - echo "Setting timezone"
      - Set-TimeZone -Id "Eastern Standard Time"
  build:
    commands:
      - echo "Compiling..."
      - javac test.java
      - javac -cp lib/mysql-connector-j-8.0.33.jar dbConnect.java
  post_build:
    commands:
      - echo "Running..."
      - echo $DATABASE_URL
      - echo $DATABASE_USERNAME
      - echo $DATABASE_PASSWORD
      - java test.java
      - java -cp ".;lib/mysql-connector-j-8.0.33.jar" dbConnect


