version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Listing contents..."
      - Get-ChildItem -Recurse
  build:
    commands:
      - echo "Compiling..."
      - javac test.java
  post_build:
    commands:
      - echo "Running..."
      - java test.java


